name: Build LaTeX document
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**.tex'


jobs:
  build_latex:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          body: Latest release
          draft: false
          files: main.pdf
